### ISSUE TITLE
An error with index.js

### ISSUE THREAD

**Issue by PrivacyDragon** [Timendus/ticalc.link#2]
I get an error in the console every time that I try to send a file, the file doesn't even arrive.
I'm using a TI-84+ CE.
The website and the calculator are reacting to each other though
![Screenshot_20201129_143143](https://user-images.githubusercontent.com/70799817/100543330-becf6480-324f-11eb-931d-3bb1a75c5f1b.png)

**Comment by Timendus** [comment]
Thanks for reporting, let's continue the discussion in #4
