### ISSUE TITLE
Unable to Progress Past Step 1

### ISSUE THREAD

**Issue by TheLastMillennial** [Timendus/ticalc.link#20]
OS: Windows 10 Home 20H2
Browser: Edge Version 89.0.774.76 (Official build) (64-bit)
Calculator: TI-84 Plus CE Revision M with OS 5.3.0

Issue: I cannot get the first step to be marked as completed. When I opened ticalc.link, the 'Select Calculator' was in blue. I clicked it, selected my calculator, and clicked 'Connect'. However, step 1 did not turn into a green check mark nor did I get any warning about the TI-84 Plus CE's support still being in beta. If I click on step 1 again, Edge will show that my calculator is currently paired.

Although step 2 was greyed out, I could still click on it and select a file. Step 2 would turn into a green check mark but step 1 would stay the same blue color. 

Step 3 is greyed out and I cannot interact with it no matter what file I select (ASM or Basic) in step 2.

The only error in the console is
```
DOMException: Access denied.
o @ index.js:1
```
Which takes me to this function. The error is the ".error(e)" on the last line. e is undefined.
``` function o(e) {

            e && "Calculator model not supported" == e.message ? l("Sorry!", "It looks like your device is not yet supported. Would you like to submit it for consideration?").then((()=>function(e) {
                document.querySelector("#flow").innerHTML = `\n    <h1>Device info to submit</h1>\n    <p>Please <a href='https://github.com/Timendus/ticalc-usb/issues/new?assignees=&labels=device+support+request&template=calculator-support-request.md&title=Calculator+support+request' target="_blank">file a support request on Github</a> with the following information:</p>\n    <pre>${JSON.stringify({
                    deviceClass: e.deviceClass,
                    deviceProtocol: e.deviceProtocol,
                    deviceSubclass: e.deviceSubclass,
                    deviceVersionMajor: e.deviceVersionMajor,
                    deviceVersionMinor: e.deviceVersionMinor,
                    deviceVersionSubminor: e.deviceVersionSubminor,
                    manufacturerName: e.manufacturerName,
                    productId: e.productId,
                    productName: e.productName,
                    serialNumber: e.serialNumber,
                    usbVersionMajor: e.usbVersionMajor,
                    usbVersionMinor: e.usbVersionMinor,
                    usbVersionSubminor: e.usbVersionSubminor,
                    vendorId: e.vendorId
                }, null, 2)}</pre>\n  `
            }(e.device))).catch((()=>{}
            )) : console.error(e)
```

**Comment by adriweb** [comment]
Did you do the usual windows-specific step regarding the filter driver and zadig?

**Comment by TheLastMillennial** [comment]
I have not, I don't see any mention of this in the readme or on the site. From what I remember, I could not get zadig to install the driver filter properly. Is there an alternative such as uninstalling TI-Connect CE?

**Comment by debrouxl** [comment]
You shouldn't have to resort to that measure, though (*). What are the issues when you use Zadig to install the libusb-win32 driver for the calculator, then the libusb-win32 filter driver installer to install the filter driver beneath the driver.

*: not yet, that is. It looks like Windows 11 will be even more of a user-annoying PITA wrt. drivers, see https://community.osr.com/discussion/293115/windows-11-and-alternative-driver-installation-method-in-libwdi .

**Comment by TheLastMillennial** [comment]
I was having an issue where Zadig couldn't allocate resources but debrouxl helped me out with this resource: https://github.com/pbatard/libwdi/issues/69 

Unfortunately even after replacing the driver and restarting my computer, I'm still having the same issue.

**Comment by Timendus** [comment]
Hey there! Thanks for reporting your issue. If you can see the calculator in the browser, and select it, I suppose in theory it should "just work". And not give a `DOMException` in the console. So maybe we just have a MS Edge specific bug. I've never tested it with Edge, and I don't think many other people have. Can you try using a different browser (preferably Google Chrome) to see if the problem persists?

**Comment by TheLastMillennial** [comment]
Thanks for your reply! I just tried the latest version of Chrome but encountered the same issues. Even the console has the same error.

Unfortunately, I cannot get the filter driver installed due to libusb-win32 filter installer not identifying my calculator. Along with [an issue](https://github.com/pbatard/libwdi/issues/163) that should be fixed in the next release of Zadig. I can't figure out how to revert to the old driver either so my calculator no longer works with TI-Connect CE.

**Comment by Timendus** [comment]
Alright, then we can rule out an issue with Edge. That's good I suppose. I haven't really used Windows in a decade or two, so I can't really help you there unfortunately. Maybe Lionel or Adrien can!

**Comment by Timendus** [comment]
> I don't see any mention of this in the readme or on the site
Good point by the way. If additional steps are required on Windows, it would be kind to tell people. It's just that I'm utterly oblivious 😄 When you figure it out, your feedback on what that message should say would be much appreciated!

**Comment by reesericci** [comment]
I needed to on linux give my user priviliges to access all usb devices before it would work, and only in Google Chrome would it work reliably.

**Comment by TheLastMillennial** [comment]
OK so I fixed my issue with ticalc.link in a weird way. You may know you can use a program called [CERMASTR](https://tiplanet.org/forum/archives_voir.php?id=1581757) to rename a calculator in the certificate. I was not having success getting libusb-win32 filter installer to detect my TI-84 Plus CE (revision M) which has the default name of 'TI-84 Plus CE'. However, when I plugged in my TI-84 Plus CE Python Edition (revision P) which I renamed to 'TI-84 KE TLM', the program recognized the calculator and I was able to install the filter driver. When I plugged my regular TI-84 Plus CE back into the computer, it's recognized as a TI-84 KE TLM which is odd.

Anyways, I opened Edge again, went to ticalc.link, and was able to progress through the steps normally and send over a file!

Not everything is working though. TI-Connect CE still no longer recognizes any of my calculators. I thought the filter driver was suppose to make ticalc.link and TI-Connect CE play nicely together but perhaps I misunderstood? Reinstalling TI-Connect CE didn't fix the issue. How should I go about fixing it?

**Comment by reesericci** [comment]
Also, when I renamed my calc with the aformentioned CERMASTR. It said that my calc wasn't supported (presumably because it uses the calc name to determine support). I had to change mine back to the default "TI-84 Plus CE" before it would work.

**Comment by TheLastMillennial** [comment]
Following a suggestion by @debrouxl installed TILP and discovered TILP will correctly recognize my renamed calculator as a TI-84 Plus CE. Perhaps ticalc.link can adopt TILP's method of identifying calculators?

**Comment by Timendus** [comment]
That's good to hear 👍

**Comment by Timendus** [comment]
I'm closing this issue for now. Feel free to open a new one if needed!
