### ISSUE TITLE
.8xv files will not transfer to TI-84 Plus CE

### ISSUE THREAD

**Issue by dragonismcode** [Timendus/ticalc.link#26]
Hey there,

I'm currently on Chrome OS (Version 94.0.4606.124) and when I try to send a .8xv file to ticalc.link, it says it has been successfully sent, yet I cannot find the file on my Calculator. Another issue I'd like to bring up is that when trying to open the file, I have to go to "All Files". This should show with the other selected files.

Thank you for your time and effort on this project.

**Comment by SqueezyS** [comment]
I too have the same issue except it says it can't send at all.

**Comment by Timendus** [comment]
Thanks for reporting! Does it work in your fork? Is it just a matter of adding the extension, or is it actually a different file format?

**Comment by Timendus** [comment]
Closed issue in favour of group issue #38. Thank you for submitting!
