### ISSUE TITLE
Programs always have error on TI-84 CE

### ISSUE THREAD

**Issue by SqueezyS** [Timendus/ticalc.link#27]
Hello,

I am able to upload programs but my inability to play them is a bit saddening. I can upload perfect, but i can't do anything with them except getting errors. Please fix this if you can, but i know you have a very limited time

Best Regards,
  Squeezy

**Comment by SqueezyS** [comment]
After some more research, this thing works 100% perfectly

I just needed arTIfiCE to launch things.

**Comment by Timendus** [comment]
Haha, great to see you solved your issue, and great to see ticalc.link works as expected for you. Thanks!
