### ISSUE TITLE
Can't send .8ek, .8ca, or .b84 files

### ISSUE THREAD

**Issue by Spaceboy10** [Timendus/ticalc.link#36]
My calc: TI-84+ CE Python (H/W revision S)
OS version: 5.7.0

.8ek files are TI-84+CE applications, .8ca files are pictures for the CE, and .b84 files are bundles (basically a fancy .zip).  I'm unable to move these to my calculator using ticalc.link.  It just says that it isn't a valid calculator file.  Could you please add support for these?

**Comment by Spaceboy10** [comment]
This also happens for .8ca files (pictures) and .b84 files (a bundle file, basically a fancy .zip).

**Comment by adriweb** [comment]
I believe this issue shouldn't be closed :)
