### ISSUE TITLE
"Expected virtual packet type 47872, but got 8 instead" when using TI-84+CE

### ISSUE THREAD

**Issue by commandblockguy** [Timendus/ticalc.link#4]
I'm getting the following error when trying to send a program to my TI-84+CE:
```
Uncaught (in promise) Expected virtual packet type 47872, but got 8 instead
(anonymous) @ index.js:formatted:207
async function (async)
(anonymous) @ index.js:formatted:195
(anonymous) @ index.js:formatted:207
```

[Here's the relevant packet capture](https://github.com/Timendus/ticalc.link/files/5627546/ticalc.link_ce.pcapng.zip).

**Comment by PrivacyDragon** [comment]
I'm having [the same problem](https://github.com/Timendus/ticalc.link/issues/2) .

**Comment by commandblockguy** [comment]
I think I've narrowed it down to [these lines](https://github.com/Timendus/ticalc-usb/blob/5354d488a3698b002050c4b68038d88f015bae7e/src/dusb/ti84series.js#L60-L62) - the library expects a DUSB_VPKT_DELAY_ACK, but the calc is returning the parameter data immediately instead.

**Comment by Timendus** [comment]
Hey there! Nice to see you trying out ticalc.link with calculators with experimental support 😄 

> the library expects a DUSB_VPKT_DELAY_ACK, but the calc is returning the parameter data immediately instead.
That's quite possible. Shouldn't be too hard to fix, but unfortunately I don't have the TI-84+ CE.

Is either of you willing to test out a branch locally, if I attempt to make a fix?

**Comment by commandblockguy** [comment]
I already have a local build set up and can help test.
I've also come up with a [possible fix for it](https://github.com/commandblockguy/ticalc-usb/tree/optional-delay-ack), which seems to work on the CE without breaking the tests. There are a few other things preventing file transfer from working on the CE, though, which I'll probably make separate issues about.

**Comment by Timendus** [comment]
Very much appreciated! 😉 I like it when people bring solution to their own issues 😄

Be warned though, as a contributor, that my time to work on this project is quite limited. Plus, I don't fully trust the tests yet, so I try to find the time to test any changes with the actual hardware. So if it takes a bit for me to respond and review your changes, that doesn't mean I don't value your work! 👍🏻🙂

Curious to see the other issues you ran into.

**Comment by PrivacyDragon** [comment]
I can also try to test, the only thing is that my debugging skills aren't really good yet😅

**Comment by PrivacyDragon** [comment]
Though I don't know how I should get a branch locally to test it..
So maybe anyone should help me with that before I can test...🙄😇

**Comment by Timendus** [comment]
Sure, no problem :)

Step one is getting a development environment running on your local machine. If you have `git` and `npm` already installed you can follow the steps in https://github.com/Timendus/ticalc-usb#developing.

After that, you can switch to commandblockguy's branch:
```bash
cd ticalc-usb
git remote add commandblockguy git@github.com:commandblockguy/ticalc-usb.git
git checkout optional-delay-ack --track commandblockguy/optional-delay-ack
```

**Comment by PrivacyDragon** [comment]
`~> git clone git@github.com:Timendus/ticalc.link.git
Cloning into 'ticalc.link'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?`

**Comment by adriweb** [comment]
You can just use the https url of his repo instead of the ssh way (git@...) I the git clone command.

**Comment by Timendus** [comment]
Hey @PrivacyDragon, maybe it's easiest to just wait until we have deployed a new version to [ticalc.link](https://ticalc.link) ;P I think we're making good progress thanks to @commandblockguy's contributions, so we should have something new to test up there in a couple of days or a week..?

**Comment by Timendus** [comment]
@PrivacyDragon I have deployed a few fixes on [ticalc.link](https://ticalc.link). I expect that some files will now successfully send, and others will not. It would be much appreciated if you could give it a try, and I'm also interested to know which files give problems and which don't so I can try to find a pattern there. Thanks!

**Comment by PrivacyDragon** [comment]
I saw the changes and will test!
I've already tested it with one file using my phone and that did work!

**Comment by Timendus** [comment]
I think that makes you the first person to **ever** send a file from their phone to their calculator 😄
